[DOT-1] added a function to speed up basic git tasks
directbuy/dotfiles pull request #1
Opened 2018-11-14 15:59 UTC by RonitRudra

This is a simple alias added with a lot of functions to automate some frequent git commands. I took the liberty of christening the branches as DOT-<number>
This is more of a crude POC than a finished script. For now it's inside the dbuy.zsh_aliases but could be moved to a script file of its own to make things more modular and clean.

**FEATURES**:
 + Commit all changes in your local branch by using *gme -c "commit message"* This would add all files and create a commit with the message *[DBUY-0001] commit message* if your branch name was DBUY-0001
+ Switch to an existing branch with *gme -b BRANCHNAME*
+ Rebase all local changes by kicking off interactive rebase using *gme -r*. This adds all local commits to the rebase so if your branch has 30 commits in it, it will rebase 30. Does away with manually counting the commit numbers when doing a rebase.
+ Rebase against the dev branch using *gme -R*. Takes care of switching to dev, pulling, switching to the branch you were working on and then rebasing against origin/dev
+ See usage and help using *gme -h*

**more to come soon**

2018-11-14 16:45 UTC, blissrage commented
This seems pretty nifty. One note, if I am reading code correctly, the rebase is predicated on 100% adherence to naming standard of commits having "[branch_name]" right?

If so, should there be some fuzziness around the brackets?

2018-11-14 21:56 UTC, RonitRudra commented
> This seems pretty nifty. One note, if I am reading code correctly, the rebase is predicated on 100% adherence to naming standard of commits having "[branch_name]" right?
> 
> If so, should there be some fuzziness around the brackets?

@blissrage the rebase is independent of the way you write your commit messages as it only looks at the log of the current branch.

2018-11-14 22:05 UTC, RonitRudra commented
@blissrage but yeah it only works for branches created off *dev* since I hard-coded that in there.
So dev --> DBUY-xxxx would work but not DBUY-xxxx -> DBUY-xxxx-child as the code now needs the parent of DBUY-xxxx-child.

2018-11-19 17:22 UTC, ghost approved these changes

2018-12-19 21:01 UTC, 2ps commented
@RonitRudra :  bump--still have comments to address.

2018-12-19 21:22 UTC, RonitRudra commented
@2ps What will had mentioned? The rebase does not depend on naming standard as it gets the commits only from the current branch. Using the standard is good practice but even without it the rebase should work normally.

2018-12-20 23:07 UTC, 2ps requested changes

2018-12-20 23:07 UTC, 2ps commented on zsh/dbuy.zsh_aliases
> +        if [ "$CURRENT_BRANCH" = "dev" ]; then
Should check for `staging`  and `master` as well.  Go ahead and switch to `[[` and `]]` around the if and use `==`.

2018-12-20 23:07 UTC, 2ps commented on zsh/dbuy.zsh_aliases
> +        if [ "$CURRENT_BRANCH" = "dev" ]; then
Or `staging` or `master`.

2019-01-16 14:49 UTC, RonitRudra commented
@2ps made the changes that you asked for -> `[[ ==` as well as checking for staging and master branches . (rebasing the commits and pushing gets rid of everyone's change requests though)

2020-09-25 03:54 UTC, merged